### ISSUE TITLE
Build failed with current crystal version

### ISSUE THREAD

**Issue by alexanderadam** [konovod/spellstorm#1]
Hi @konovod, I would love to have a look at the project but the build fails with current crystal. Any idea how to fix this?

```
Error in src/spellstorm.cr:3: instantiating 'Spellstorm::SpellstormGame:Class#new()'

instance = Spellstorm::SpellstormGame.new
                                      ^~~

in src/spellstorm/game.cr:63: instantiating 'super()'

      super
      ^~~~~

in src/spellstorm/engine/engine.cr:40: instantiating 'SF::RenderWindow:Class#new(SF::VideoMode, String)'

      @window = SF::RenderWindow.new(SF::VideoMode.new(SCREENX, SCREENY), "My window")
                                 ^~~

in lib/crsfml/src/graphics/obj.cr:5232: instantiating 'SF::ContextSettings:Class#new()'

    def self.new(mode : VideoMode, title : String, style : Style = Style::Default, settings : ContextSettings = ContextSettings.new()) : self
                                                                                                                                ^~~

in lib/crsfml/src/window/obj.cr:101: can't restrict SF::ContextSettings::Attribute to Int

    def initialize(depth : Int = 0, stencil : Int = 0, antialiasing : Int = 0, major : Int = 1, minor : Int = 1, attributes : Int = Default, s_rgb : Bool = false)
```

Have a nice day!

**Comment by konovod** [comment]
fixed now (updated crsfml to compatible version)
project didn't get to playable stage though (I get stuck on UI layout), so there is not much to see.

**Comment by alexanderadam** [comment]
Awesome @konovod, thank you!
I see  but still interesting! Works like charm.

If I may ask: Did you create a game you finished and have it on GitHub? If so: with crystal or something else?

**Comment by konovod** [comment]
on github - only https://github.com/konovod/borderline/ so far. Still nothing finished in crystal, but i hope to complete something at least at the day when Windows support in crystal become stable.
I have several games on sourceforge and other places, in pascal, ruby and dlang, i think this list includes most of them: http://www.gamedev.ru/users/?id=49958 (it's in russian, but most games are in english).

**Comment by alexanderadam** [comment]
Thank you. I totally forgot that we probably can close this issue here 😉 
Have a nice day!
